### ISSUE TITLE
Error after launch RUN.bat

### ISSUE THREAD

**Issue by EternalRubis** [BayGamerYT/Fortnite-LobbyBot-v2#7]
V1.5.3.1
Python 3.11.2
fortnitepy 3.6.4
discord.py 2.2.2
Sanic 22.12.0
Traceback (most recent call last):
  File "C:\Users\Dsden23\Documents\Projets\Fortnite-LobbyBot-v2\index.py", line 91, in <module>
    bot = modules.Bot(
          ^^^^^^^^^^^^
  File "C:\Users\Dsden23\Documents\Projets\Fortnite-LobbyBot-v2\modules\bot.py", line 146, in __init__
    self.input_lock = asyncio.Lock(loop=loop)
                      ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Lock.__init__() got an unexpected keyword argument 'loop'

**Comment by EternalRubis** [comment]
what can i do for resolve this error ?

**Comment by Not-Bay** [comment]
You are using Python 3.11 and FLB is compatible up to 3.9

Here is latest 3.9 with official binaries https://www.python.org/downloads/release/python-3913/

**Comment by EternalRubis** [comment]
Thx

**Comment by EternalRubis** [comment]
![image](https://user-images.githubusercontent.com/111808522/229315320-b2a85317-bc97-49f6-85df-a41d8a2c77c0.png)

After this, the bot is on ?

**Comment by EternalRubis** [comment]
So, the bot, is on and in my group. But how can i get ready when i want to start a game ?

**Comment by EternalRubis** [comment]
i know i have write "ready" in the chat, but the game didn't start. how can i fix it ? 
![image](https://user-images.githubusercontent.com/111808522/229318921-ee90a2de-b045-471d-b76e-9ee3ca1e83ee.png)

**Comment by Huguitis** [comment]
You can not enter to a match

**Comment by EternalRubis** [comment]
But, BayGamerYT (1 to 6) can launch a bot lobbies, so why with the repo I can"t ?

**Comment by Not-Bay** [comment]
Sorry but FLB doesn't support matchmaking. 
The stuff needed to "launch bot lobbies" is not and likely never be supported by fortnitepy (the library FLB use to run bots)

**Comment by EternalRubis** [comment]
So, where can i find it and make it for launch game ?

**Comment by Not-Bay** [comment]
You may not be able to find anything, at least open source.

Closing this issue since the initial problem is fixed.
