### ISSUE TITLE
Matchmaking support.

### ISSUE THREAD

**Issue by Huguitis** [BayGamerYT/Fortnite-LobbyBot-v2#9]
Add matchmaking system support to join games using the endpoint: (Everything configurable)
```
https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/game/v2/matchmakingservice/ticket/player/<user id>
```

**Comment by Not-Bay** [comment]
I already answered this on the support server but to close the issue i will say it here.

Epic does not agree with bots (or scripts) interacting in any way with the matchmaking service.
So, i will not facilitate or provide support in cases where the game's matchmaking is touched.
